# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x1c\n\tuserQuery\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cuserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\tchatRoute\x12\x35\n\x08userChat\x12\x0f.chat.userQuery\x1a\x12.chat.userResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERQUERY']._serialized_start=20
  _globals['_USERQUERY']._serialized_end=48
  _globals['_USERRESPONSE']._serialized_start=50
  _globals['_USERRESPONSE']._serialized_end=81
  _globals['_CHATROUTE']._serialized_start=83
  _globals['_CHATROUTE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
