# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"[\n\tuserQuery\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x16\n\x0eis_human_reply\x18\x04 \x01(\x08\"U\n\x0cuserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12 \n\x04kind\x18\x02 \x01(\x0e\x32\x12.chat.ResponseKind\x12\x12\n\nsession_id\x18\x03 \x01(\t\"(\n\x12\x63hatHistoryRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x90\x01\n\x11storedChatMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x11\n\tfile_path\x18\x05 \x01(\t\x12\x15\n\rresponse_kind\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"@\n\x13\x63hatHistoryResponse\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.chat.storedChatMessage\"\x19\n\x17\x63learChatHistoryRequest\"<\n\x18\x63learChatHistoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*j\n\x0cResponseKind\x12\x1d\n\x19RESPONSE_KIND_UNSPECIFIED\x10\x00\x12\x15\n\x11\x41SSISTANT_MESSAGE\x10\x01\x12\x19\n\x15\x43LARIFICATION_REQUEST\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\xde\x01\n\tchatRoute\x12\x33\n\x08userChat\x12\x0f.chat.userQuery\x1a\x12.chat.userResponse\"\x00\x30\x01\x12G\n\x0egetChatHistory\x12\x18.chat.chatHistoryRequest\x1a\x19.chat.chatHistoryResponse\"\x00\x12S\n\x10\x63learChatHistory\x12\x1d.chat.clearChatHistoryRequest\x1a\x1e.chat.clearChatHistoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSEKIND']._serialized_start=544
  _globals['_RESPONSEKIND']._serialized_end=650
  _globals['_USERQUERY']._serialized_start=20
  _globals['_USERQUERY']._serialized_end=111
  _globals['_USERRESPONSE']._serialized_start=113
  _globals['_USERRESPONSE']._serialized_end=198
  _globals['_CHATHISTORYREQUEST']._serialized_start=200
  _globals['_CHATHISTORYREQUEST']._serialized_end=240
  _globals['_STOREDCHATMESSAGE']._serialized_start=243
  _globals['_STOREDCHATMESSAGE']._serialized_end=387
  _globals['_CHATHISTORYRESPONSE']._serialized_start=389
  _globals['_CHATHISTORYRESPONSE']._serialized_end=453
  _globals['_CLEARCHATHISTORYREQUEST']._serialized_start=455
  _globals['_CLEARCHATHISTORYREQUEST']._serialized_end=480
  _globals['_CLEARCHATHISTORYRESPONSE']._serialized_start=482
  _globals['_CLEARCHATHISTORYRESPONSE']._serialized_end=542
  _globals['_CHATROUTE']._serialized_start=653
  _globals['_CHATROUTE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
