from fastmcp import FastMCP
from pptx import Presentation
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from pathlib import Path
import uuid

mcp = FastMCP("Generation MCP Server")
OUTPUT_DIR = Path(__file__).resolve().parents[1] / "outputs"


def output_path(file_name):
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    return OUTPUT_DIR / file_name


def saved_file_response(message, file_path, details):
    detail_lines = "\n".join(
        f"{label}: {value}"
        for label, value in details.items()
    )

    return (
        f"{message}\n\n"
        f"Saved to:\n{file_path}\n\n"
        f"{detail_lines}"
    )


@mcp.tool()
def generate_powerpoint(title: str, slides: list[dict]) -> str:
    """
    Generate a PowerPoint file from structured slide data.

    slides format:
    [
        {
            "title": "Slide title",
            "bullet_points": ["point 1", "point 2"]
        }
    ]

    Returns the saved .pptx file path.
    """

    if not isinstance(slides, list):
        return "Error: Cannot generate PowerPoint because slides must be a list."

    valid_slides = []
    for slide in slides:
        if not isinstance(slide, dict):
            continue

        slide_title = str(slide.get("title", "")).strip()
        bullet_points = slide.get("bullet_points", [])

        if isinstance(bullet_points, str):
            bullet_points = [bullet_points]

        if not isinstance(bullet_points, list):
            continue

        clean_points = [
            str(point).strip()
            for point in bullet_points
            if str(point).strip()
        ]

        if slide_title and clean_points:
            valid_slides.append(
                {
                    "title": slide_title,
                    "bullet_points": clean_points,
                }
            )

    if not valid_slides:
        return "Error: Cannot generate PowerPoint because no slide content was provided."

    prs = Presentation()

    # Title slide
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by Local Video Analyst"

    # Content slides
    content_layout = prs.slide_layouts[1]

    for slide_data in valid_slides:
        slide = prs.slides.add_slide(content_layout)

        slide_title = slide_data.get("title", "Untitled Slide")
        bullet_points = slide_data.get("bullet_points", [])

        slide.shapes.title.text = slide_title

        body = slide.placeholders[1]
        text_frame = body.text_frame
        text_frame.clear()

        for point in bullet_points:
            p = text_frame.add_paragraph()
            p.text = str(point)
            p.level = 0

    file_path = output_path(f"video_summary_{uuid.uuid4().hex[:8]}.pptx")
    prs.save(file_path)

    return saved_file_response(
        message="PowerPoint generated successfully.",
        file_path=file_path.resolve(),
        details={
            "Type": "PowerPoint presentation",
            "Title": title,
            "Slides": len(valid_slides) + 1,
        },
    )


@mcp.tool()
def generate_pdf(title: str, summary: str) -> str:
    """
    Generate a PDF report from a title and context summary.

    Returns the saved .pdf file path.
    """

    file_path = output_path(f"discussion_summary_{uuid.uuid4().hex[:8]}.pdf")
    doc = SimpleDocTemplate(str(file_path), pagesize=A4)
    styles = getSampleStyleSheet()

    elements = []
    paragraph_count = 0

    elements.append(Paragraph(title, styles["Title"]))
    elements.append(Spacer(1, 12))

    for paragraph in summary.split("\n"):
        paragraph = paragraph.strip()
        if paragraph:
            elements.append(Paragraph(paragraph, styles["BodyText"]))
            elements.append(Spacer(1, 8))
            paragraph_count += 1

    doc.build(elements)

    return saved_file_response(
        message="PDF generated successfully.",
        file_path=file_path.resolve(),
        details={
            "Type": "PDF report",
            "Title": title,
            "Paragraphs": paragraph_count,
        },
    )


if __name__ == "__main__":
    mcp.run()
